apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: juphub
spec:
  selector:
    app: jupyterhub
  clusterIP: None
  ports:
  - name: notebook
    port: 8888
    targetPort: 8888
  - name: comm
    port: 39777 
    targetPort: 39777
  - name: blockmngr
    port: 6060
    targetPort: 6060